sudo: false
language: node_js
node_js:
- 4
- stable
cache: yarn
before_install:
# try-resolve won't work on examples
# we will fix example symlink by npm@5
- npm install -g npm@4
- npm install -g yarn@latest
install:
- yarn install
- yarn run bootstrap
script:
- yarn test:all
